name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login benhadji99 -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and Push Docker Image
      run: |
        docker build -t benhadji99/my-app:latest .
        docker push benhadji99/my-app:latest
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
    - name: Deploy to Kubernetes
      run: |
        kubectl config set-context --current --namespace=default
        kubectl apply -f deployment.yaml